---
- name: install accounts service
  tags: accounts
  pacman:
    name: "accountsservice"
    state: present

- name: write user face icons for accounts service
  tags: accounts
  copy:
    src: face.png
    dest: "/var/lib/AccountsService/icons/{{ user_name }}.png"
    owner: root
    group: root
    mode: 0644

- name: write user icons path for accounts service
  tags: accounts
  template:
    src: accounts.j2
    dest: "/var/lib/AccountsService/users/{{ user_name }}"
    owner: root
    group: root
    mode: 0644

- name: symlink user face icons in home
  tags: accounts
  file:
    src: "/var/lib/AccountsService/icons/{{ user_name }}.png"
    dest: "/home/{{ user_name }}/.face"
    state: link
