---
- name: write user face icons for accounts service
  tags: accounts
  copy:
    src: face.png
    dest: "/var/lib/AccountsService/icons/{{ user_name }}"
    owner: root
    group: root
    mode: 0644

- name: symlink user face icons in home
  tags: accounts
  file:
    src: "/var/lib/AccountsService/icons/{{ user_name }}"
    dest: "/home/{{ user_name }}/.face"
    state: link
