---
- name: install alsa-utils
  tags: audio
  pacman:
    name: "alsa-utils"
    state: present

- name: install pulseaudio
  tags: audio
  pacman:
    name: "pulseaudio,pulseaudio-alsa"
    state: present

- name: install gstreamer
  tags: audio
  pacman:
    name: "gstreamer,gst-plugins-good,gst-plugins-base"
    state: present

- name: install ffmpeg
  tags: audio
  pacman:
    name: "ffmpeg,ffmpegthumbnailer"
    state: present

- name: install pavucontrol
  tags: audio
  pacman:
    name: "pavucontrol"
    state: present

- name: install volumeicon
  tags: audio
  pacman:
    name: "volumeicon"
    state: present
