---
- name: install alsa-utils
  tags: audio
  pacman:
    name: "alsa-utils"
    state: present

- name: install pulseaudio
  tags: audio
  pacman:
    name: "pulseaudio,pulseaudio-alsa"
    state: present

- name: install pavucontrol
  tags: audio
  pacman:
    name: "pavucontrol,xfce4-mixer"
    state: present