---
- name: install vanilla cursor themes
  tags: cursor
  pacman:
    name: xcursor-vanilla-dmz
    state: present

- name: update default cursor themes
  tags: cursor
  file:
    src: "/usr/share/icons/{{ xorg_cursor_theme }}/cursors"
    dest: "/usr/share/icons/default/cursors"
    owner: root
    group: root
    mode: 0644
    state: link

- name: install faenza icon themes
  tags: icon
  pacman:
    name: "faenza-icon-theme"
    state: present

- name: download autumn-leaves wallpaper themes
  tags: wallpaper
  get_url:
    url: "{{ autumn_leaves_url }}"
    dest: "{{ autumn_leaves_path }}"
    checksum: "sha256:{{ autumn_leaves_sha256 }}"

- name: install autumn-leaves wallpaper themes
  tags: wallpaper
  pacman:
    name: "{{ autumn_leaves_path }}"
    state: present

- name: download cookie wallpaper themes
  tags: wallpaper
  get_url:
    url: "{{ cookie_wallpapers_url }}"
    dest: "{{ cookie_wallpapers_path }}"
    checksum: "sha256:{{ cookie_wallpapers_sha256 }}"

- name: install cookie wallpaper themes
  tags: wallpaper
  pacman:
    name: "{{ cookie_wallpapers_path }}"
    state: present

- name: download Vertex gtk themes
  tags: gtk
  get_url:
    url: "{{ vertex_url }}"
    dest: "{{ vertex_path }}"
    checksum: "sha256:{{ vertex_sha256 }}"

- name: install Vertex gtk themes
  tags: gtk
  pacman:
    name: "{{ vertex_path }}"
    state: present

- name: download Flat Remix gtk and icon themes
  tags: gtk
  get_url:
    url: "{{ flat_remix_url }}"
    dest: "{{ flat_remix_path }}"
    checksum: "sha256:{{ flat_remix_sha256 }}"

- name: install Flat Remix gtk and icon themes
  tags: gtk
  pacman:
    name: "{{ flat_remix_path }}"
    state: present
