---
- name: install grub with pacman
  tags: grub
  pacman:
    name: grub
    state: present
    update_cache: yes
  register: grub_install

- name: install grub on MBR
  tags: grub
  command: "grub-install --no-floppy --recheck {{ grub.fs }}"
  when: grub_install|changed

- name: update /etc/default/grub configuration
  tags: grub
  lineinfile:
    dest: /etc/default/grub
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  with_items: grub.options
  register: grub_default

- name: update grub configuration
  tags: grub
  command: grub-mkconfig -o /boot/grub/grub.cfg
  when: grub_default|changed