---
xorg_cursor_theme: "Vanilla-DMZ"
xorg_keyboard_conf_path: "/etc/X11/xorg.conf.d/00-keyboard.conf"
xorg_touchpad_conf_path: "/etc/X11/xorg.conf.d/30-touchpad.conf"
profile_directory: "/etc/profile.d/"
backgrounds_directory: "/usr/share/backgrounds"
lightdm_background_path: "{{ backgrounds_directory }}/autumn-leaves/2560x1600.jpg"
lightdm_theme_name: "Vertex-Dark"
lightdm_icon_name: "Faenza"
lightdm_display_setup_path: "/usr/local/sbin/lightdm-display"
xflock4_path: "/usr/local/bin/xflock4"
xflock4_command: "dm-tool lock"
user_cache_path: "/home/{{ user_name }}/.cache"
xfce4_session_path: "{{ user_cache_path }}/.cache/sessions"
xfconf_root_path: "/home/{{ user_name }}/.config/xfce4/xfconf/xfce-perchannel-xml"
xfconf_xsettings_path: "{{ xfconf_root_path }}/xsettings.xml"
xfconf_xfwm4_path: "{{ xfconf_root_path }}/xfwm4.xml"
xfconf_xfce4_panel_path: "{{ xfconf_root_path }}/xfce4-panel.xml"
xfconf_xfce4_desktop_path: "{{ xfconf_root_path }}/xfce4-desktop.xml"
xfconf_xfce4_power_manager_path: "{{ xfconf_root_path }}/xfce4-power-manager.xml"
xfconf_xfce4_session_path: "{{ xfconf_root_path }}/xfce4-session.xml"
xfconf_xfce4_thunar_path: "{{ xfconf_root_path }}/thunar.xml"
xfconf_xfce4_pointers_path: "{{ xfconf_root_path }}/pointers.xml"
xfconf_xfce4_keyboard_shortcuts_path: "{{ xfconf_root_path }}/xfce4-keyboard-shortcuts.xml"
xfce4_terminal_directory: "/home/{{ user_name }}/.config/xfce4/terminal"
xfce4_terminal_path: "{{ xfce4_terminal_directory }}/terminalrc"
pacman_pkg_cache_path: "/var/cache/pacman/pkg"
kma_assets_url: "https://github.com/novln/Kiss-my-Arch/raw/master/assets"
autumn_leaves_pkgname: "autumn-leaves"
autumn_leaves_pkgver: "1.0.0"
autumn_leaves_pkgrel: "2"
autumn_leaves_sha256: "e01aa20458afec368cd75520aacf0aa71b20f070625c8755586c1438c6f05f9a"
autumn_leaves_pkg: "{{ autumn_leaves_pkgname }}-{{ autumn_leaves_pkgver }}-{{ autumn_leaves_pkgrel }}-any.pkg.tar.xz"
autumn_leaves_url: "{{ kma_assets_url }}/{{ autumn_leaves_pkgname }}/{{ autumn_leaves_pkg }}"
autumn_leaves_path: "{{ pacman_pkg_cache_path }}/{{ autumn_leaves_pkg }}"
cookie_wallpapers_pkgname: "cookie-wallpapers"
cookie_wallpapers_pkgver: "1.0.0"
cookie_wallpapers_pkgrel: "1"
cookie_wallpapers_sha256: "92909cb5eed370cd2d437f89a7ec3f4a3666fdc62df6ba082495b820558f0008"
cookie_wallpapers_pkg: "{{ cookie_wallpapers_pkgname }}-{{ cookie_wallpapers_pkgver }}-{{ cookie_wallpapers_pkgrel }}-any.pkg.tar.xz"
cookie_wallpapers_url: "{{ kma_assets_url }}/{{ cookie_wallpapers_pkgname }}/{{ cookie_wallpapers_pkg }}"
cookie_wallpapers_path: "{{ pacman_pkg_cache_path }}/{{ cookie_wallpapers_pkg }}"
vertex_pkgname: "vertex-themes"
vertex_pkgver: "20190828"
vertex_pkgrel: "0"
vertex_sha256: "1f9b4e52adac3de56c178eb76bf64d4c632280bf0ccf0070acd184ab4db48781"
vertex_pkg: "{{ vertex_pkgname }}-{{ vertex_pkgver }}-{{ vertex_pkgrel }}-any.pkg.tar.xz"
vertex_url: "{{ kma_assets_url }}/{{ vertex_pkgname }}/{{ vertex_pkg }}"
vertex_path: "{{ pacman_pkg_cache_path }}/{{ vertex_pkg }}"
flat_remix_pkgname: "flat-remix-themes"
flat_remix_pkgver: "20201218"
flat_remix_pkgrel: "0"
flat_remix_sha256: "085318be2079871b64705c67d57192d0790d6a197e5bd41c2b70002448fc504f"
flat_remix_pkg: "{{ flat_remix_pkgname }}-{{ flat_remix_pkgver }}-{{ flat_remix_pkgrel }}-any.pkg.tar.zst"
flat_remix_url: "{{ kma_assets_url }}/{{ flat_remix_pkgname }}/{{ flat_remix_pkg }}"
flat_remix_path: "{{ pacman_pkg_cache_path }}/{{ flat_remix_pkg }}"
kitty_root_path: "/home/{{ user_name }}/.config/kitty"
kitty_conf_path: "/home/{{ user_name }}/.config/kitty/kitty.conf"
