---
- name: install docker with pacman
  tags: docker
  pacman:
    name: "docker"
    state: present

- name: add user in docker group
  tags: docker
  user:
    append: yes
    name: "{{ user_name }}"
    groups: docker

- name: enable docker
  tags: docker
  service:
    name: docker
    enabled: yes

- name: install docker-compose with pacman
  tags: docker
  pacman:
    name: "docker-compose"
    state: present
