---
- name: install git with pacman
  tags: git
  pacman:
    name: "git"
    state: present
  register: install_git

- name: configure git
  tags: git
  shell: "su - {{ user_name }} -c '{{ item }}'"
  when: install_git|changed
  with_items:
    - 'git config --global user.name "{{ git_user_name }}"'
    - 'git config --global user.email "{{ git_user_email }}"'
    - 'git config --global push.default simple'

# git config --global user.name "Thomas LE ROUX"
#   238  git config --global user.name "Thomas LE ROUX"
#   239  git config --global user.email "thomas@november-eleven.fr"
#git config --global push.default simple