---
- name: install git with pacman
  tags: git
  pacman:
    name: "git"
    state: present

- name: configure gitconfig
  tags: git
  template:
    src: gitconfig.j2
    dest: "{{ git_configuration_path }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0644

- name: configure git for zsh
  tags: git
  template:
    src: "zshrc.d/git.zsh.j2"
    dest: "{{ zsh_configuration_directory }}/git.zsh"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0644

- name: create ssh directory
  tags: git
  file:
    path: "{{ ssh_directory }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0700

- name: generate new rsa keys for user
  tags: git
  shell: "ssh-keygen -q -t rsa -b {{ ssh_key_size }} -N '{{ ssh_key_passphrase | default('') }}' -f {{ ssh_key_path }}"
  args:
    creates: "{{ ssh_key_path }}"
  become: true
  become_user: "{{ user_name }}"
