---
- name: install vlc with pacman
  tags: vlc
  pacman:
    name: "vlc,twolame"
    state: present

- name: install zip with pacman
  tags: zip
  pacman:
    name: "zip,unzip"
    state: present

- name: install 7zip with pacman
  tags: 7zip
  pacman:
    name: "p7zip"
    state: present

- name: install youtube-dl with pacman
  tags: youtube-dl
  pacman:
    name: "youtube-dl"
    state: present

- name: configure youtube-dl for zsh
  tags: youtube-dl
  template:
    src: "zprofile.d/youtube-dl.zsh.j2"
    dest: "{{ zsh_configuration_directory }}/youtube-dl.zsh"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0644
