---
- name: create ssh directory
  tags: ssh
  file:
    path: "{{ ssh_directory }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0700

- name: generate new rsa keys for user
  tags: ssh
  shell: "ssh-keygen -q -t rsa -b {{ ssh_key_size }} -N '{{ ssh_key_passphrase | default('') }}' -f {{ ssh_key_path }}"
  args:
    creates: "{{ ssh_key_path }}"
  become: true
  become_user: "{{ user_name }}"

- name: create ssh config for user
  tags: ssh
  template:
    src: ssh-config.j2
    dest: "{{ ssh_config_path }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0644
