---
- name: install virtualbox for host
  tags: virtualbox
  pacman:
    name: "virtualbox-host-modules-arch,virtualbox,net-tools"
    state: present
  when: ansible_virtualization_role == "host"

- name: install virtualbox utils for guest
  tags: virtualbox
  pacman:
    name: "virtualbox-guest-modules-arch,virtualbox-guest-utils"
    state: present
  when: ansible_virtualization_role == "guest"

- name: enable virtualbox service for guest
  tags: virtualbox
  service:
    name: vboxservice
    enabled: yes
  when: ansible_virtualization_role == "guest"

- name: add user in vboxusers group
  tags: virtualbox
  user:
    append: yes
    name: "{{ user_name }}"
    groups: vboxusers
  when: ansible_virtualization_role == "host"
