---
- name: install dhclient with pacman
  tags: network
  pacman:
    name: "dhclient"
    state: present

- name: configure dhclient for NetworkManager
  tags: network
  template:
    src: dhcp-client.conf.j2
    dest: /etc/NetworkManager/conf.d/dhcp-client.conf
    owner: root
    group: root
    mode: 0644
