---
- name: delete root password
  tags: user
  user:
    name: root
    password: "*"

- name: configure root shell with bash
  tags: user
  user:
    name: root
    shell: "{{ bash_bin_path }}"

- name: configure user shell with zsh
  tags: user
  user:
    name: "{{ user_name }}"
    shell: "{{ zsh_bin_path }}"
