---
- name: create user
  tags: user
  user:
    name: "{{ user_name }}"
    comment: "{{ user_comment }}"
    shell: /bin/bash
    password: "{{ user_password }}"

- name: add user to default groups
  tags: user
  user:
    name: "{{ user_name }}"
    append: yes
    groups: "log,audio,lp,storage,systemd-journal,users,wheel"