---
- name: create user
  tags: user
  user:
    name: "{{ user_name }}"
    comment: "{{ user_comment }}"
    shell: /bin/bash
    append: yes
    group: "{{ user_name }}"
    groups: "log,audio,lp,storage,systemd-journal,users,wheel"
    password: "{{ user_password }}"